### MultiOutput Regression Models In Python

In [1]:
##https://machinelearningmastery.com/multi-output-regression-models-with-python/
from sklearn.datasets import make_regression


In [2]:
## Create the dataset
X,y =make_regression(n_samples=1500,n_informative=5,n_features=10,n_targets=2)

In [3]:
X

array([[-0.03136653, -0.35900981, -1.67306523, ...,  1.56954316,
         2.26556503,  1.45872778],
       [ 0.29418171,  1.68505524,  0.53589358, ...,  1.93240131,
         0.10836695,  0.34002295],
       [-2.04977257,  1.61848881,  0.25457167, ..., -0.04524901,
        -1.73243247,  1.49340806],
       ...,
       [ 0.57800618,  1.26492697, -0.63069299, ...,  0.18989181,
         0.21727002,  0.18580876],
       [-1.20187793,  2.00548944,  0.2680721 , ...,  0.86585819,
         0.24316888, -2.10329723],
       [-0.75774142,  0.22107107,  0.40911666, ..., -0.27308365,
        -0.67249921, -0.98424163]])

In [4]:
y

array([[ 153.19843947,  231.18331512],
       [ 122.18764645,  254.10611029],
       [  72.20908477,   65.07128603],
       ...,
       [  82.47203416,   63.8637164 ],
       [-205.44231995, -159.71377526],
       [ -70.22747048, -158.5890014 ]])

### Apply Linear Regression

In [5]:
from sklearn.linear_model import LinearRegression

In [6]:
lrregression=LinearRegression()
lrregression.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
test_data=[[-0.35383149,  0.39382202, -2.03033197,  0.08873402, -0.38576581,
        0.0032707 , -0.56476034, -0.67236167,  0.31317233,  1.5208706 ]]

In [8]:
lrregression.predict(test_data)

array([[49.2659136 , 49.80375949]])

### Decision Tree Regression

In [9]:
from sklearn.tree import DecisionTreeRegressor
dtregressor=DecisionTreeRegressor()
dtregressor.fit(X,y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [10]:
dtregressor.predict(test_data)

array([[ 49.88891007, 113.08004668]])

### Random Forest Regressor

In [11]:
from sklearn.ensemble import RandomForestRegressor
rdregressor=RandomForestRegressor()
rdregressor.fit(X,y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [12]:
rdregressor.predict(test_data)

array([[57.5844358 , 74.51655314]])

## CrossValidation

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
scores=cross_val_score(rdregressor,X,y,scoring='neg_mean_squared_error',cv=5)

In [15]:
print(scores)

[-1139.90535776 -1068.27837283  -891.53348066  -863.84880432
  -951.34629988]


### All Algorithms does not support Multioutput Regressor

In [16]:
from sklearn.svm import LinearSVR
svregressor=LinearSVR()
svregressor.fit(X,y)

ValueError: bad input shape (1500, 2)

### MultiOutput Regressor sklearn

In [ ]:
from sklearn.multioutput import MultiOutputRegressor

In [ ]:
mulregressor=MultiOutputRegressor(svregressor)
mulregressor.fit(X,y)

In [ ]:
mulregressor.predict(test_data)

# Method -2

In [17]:
## Libraries

import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor


Bad key "text.kerning_factor" on line 4 in
C:\Users\hp\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution


In [18]:
#Create a random dataset

rng = np.random.RandomState(1)
X = np.sort(200 * rng.rand(600, 1) - 100, axis=0)
y = np.array([np.pi * np.sin(X).ravel(), np.pi * np.cos(X).ravel()]).T
y += (0.5 - rng.rand(*y.shape))

X_train, X_test, y_train, y_test = train_test_split(
X, y, train_size=400, test_size=200, random_state=4)

max_depth = 30
regr_multirf = MultiOutputRegressor(RandomForestRegressor(n_estimators=100,
max_depth=max_depth,
random_state=0))
regr_multirf.fit(X_train, y_train)

regr_rf = RandomForestRegressor(n_estimators=100, max_depth=max_depth,
random_state=2)
regr_rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=30, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=2, verbose=0, warm_start=False)

In [19]:
##Predict on new data

y_multirf = regr_multirf.predict(X_test)
y_rf = regr_rf.predict(X_test)

In [20]:
##Plot the results

plt.figure()
s = 50
a = 0.4
plt.scatter(y_test[:, 0], y_test[:, 1], edgecolor=‘k’,
c=“navy”, s=s, marker=“s”, alpha=a, label=“Data”)
plt.scatter(y_multirf[:, 0], y_multirf[:, 1], edgecolor=‘k’,
c=“cornflowerblue”, s=s, alpha=a,
label=“Multi RF score=%.2f” % regr_multirf.score(X_test, y_test))
plt.scatter(y_rf[:, 0], y_rf[:, 1], edgecolor=‘k’,
c=“c”, s=s, marker="^", alpha=a,
label=“RF score=%.2f” % regr_rf.score(X_test, y_test))
plt.xlim([-6, 6])
plt.ylim([-6, 6])
plt.xlabel(“target 1”)
plt.ylabel(“target 2”)
plt.title(“Comparing random forests and the multi-output meta estimator”)
plt.legend()
plt.show()

SyntaxError: invalid character in identifier (<ipython-input-20-b8600a7337de>, line 6)